import numpy as np
NR=int(input('enter the no of rows'))
NC=int(input('enter the no of coloumns'))
print("enter the entries in a single line seperated by  space")
entries=list(map(int,input().split()))
A=np.array(entries).reshape(NR,NC)
A_inverse=np.linalg.inv(A)
Transpose_of_A_inverse=np.linalg.transpose(A_inverse)
Determinant_of_A=np.linalg.det(A)
Cofactor_of_A=np.dot(Transpose_of_A_inverse,Determinant_of_A)
print("the cofactor of matrix A is ",'\n',Cofactor_of_A)
print("thedeterminant of A is",'\n',Determinant_of_A)
Adjoint_of_A=np.transpose(Cofactor_of_A)
print('transpose','\n',Adjoint_of_)
